Enough verbosity to diagnose the problem.
In gpg 1.4.12 a status message is introduced which makes python-gnupg
freak out:
    ValueError: Unknown status message: u'DECRYPTION_INFO'
I'll handle this in a personal branch of that module for now:
    git://github.com/maxrp/gnupg.git